apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            in_cluster: true

    output.elasticsearch:
      hosts: ["http://elasticsearch.default.svc.cluster.local:9200"]
      username: "elastic"
      password: "changeme"

    setup.kibana:
      host: "http://kibana.default.svc.cluster.local:5601"
