global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes'
    kubernetes_sd_configs:
      - role: pod

  - job_name: 'flask-mongo-app'
    static_configs:
      - targets: ['flask-mongo-service.default.svc.cluster.local:5000']
